import type { GameModule, Player } from "./types";
export { chessModule } from "./chessModule";
export { crazy8Module } from "./crazy8Module";
export { flappyBirdModule } from "./flappyBirdModule";
export { connect4Module } from "./connect4Module";
export { snakeLadderModule } from "./snakeLadderModule";
export { checkersModule } from "./checkersModule";
export { ludoModule } from "./ludoModule";
export { whotModule } from "./whotModule";
export { ayoModule } from "./ayoModule";
